### ISSUE TITLE
Processing Requests

### ISSUE THREAD

**Issue by patrickmedaugh** [MLee21/Traffic_Spy#2]

**Comment by mihir787** [comment]
As a user
When I submit a POST request to http://yourapplication:port/sources/INDENTIFIER/data where IDENTIFIER is unique generated previously for this site.  This request will have a parameter 'payload'(JSON data).

Then I expect to receive Success - 200 OK (if unique payload)
And the response body will look like: 200 OK

As a user
When I submit a POST request to http://yourapplication:port/sources/INDENTIFIER/data where the payload is missing.  

Then I expect to receive a status of 400 Bad Request
Response body with descriptive error message:  400 Bad Request Payload is missing

As a User 
When I submit a POST request to http://yourapplication:port/sources/INDENTIFIER/data where the payload has already been received.

Then I expect to receive a status of 403 Forbidden
Response body with descriptive error message: Payload Has Already Been Received - 403 Forbidden

As a User 
When I submit a POST request to http://yourapplication:port/sources/INDENTIFIER/data where the URL does not exist.

Then I expect to receive a status of 403 Forbidden
Response body with descriptive error message: URL does not exist-  403 Forbidden
