### ISSUE TITLE
Viewing Data & Statistics

### ISSUE THREAD

**Issue by patrickmedaugh** [MLee21/Traffic_Spy#3]

**Comment by patrickmedaugh** [comment]
As a user
When I send a GET request to http://yourapplication:port/sources/IDENTIFIER with an identifier that exists
Then I expect to see a page displaying the following:
    Most requested URLS to least requested URLS (url)
    Web browser breakdown across all requests (userAgent)
    OS breakdown across all requests (userAgent)
    Screen Resolution across all requests (resolutionWidth x resolutionHeight)
    Longest, average response time per URL to shortest, average response time per URL
    Hyperlinks of each url to view url specific data
    Hyperlink to view aggregate event data

As a user
When I send a GET request to http://yourapplication:port/sources/IDENTIFIER with an identifier that does not exist
Then I expect to see a message that the identifier does not exist

As a user
When I send a GET request to http://yourapplication:port/sources/IDENTIFIER/urls/RELATIVE/PATH with a URL that exists
Then I expect to see a page displaying the following data
  Longest response time
  Shortest response time
  Average response time 
  Which HTTP verbs have been used
  Most popular referrrers
  Most popular user agents

As a user
When I send a GET request to http://yourapplication:port/sources/IDENTIFIER/urls/RELATIVE/PATH with a URL that does not exist
Then I expect to see a message that the URL has not been requested

**Comment by MLee21** [comment]
ALSO, FIX CONDITIONAL FOR NO URL
